### ISSUE TITLE
Update problem with SPARQL Update on Virtuoso 6.x

### ISSUE THREAD

**Issue by TortugaAttack** [dice-group/IGUANA#10]
Virtuoso 6.x won't update live data due to following error

``` html
Exception: Could not update: 400 Bad Request
Virtuoso 22023 Error The request does not contain text of SPARQL query
```

Even though the query is validated.

Endpoint: sparql-auth
User and password are correct

This can either be a bug in virtuoso 6.x or in wookieConnections connect to the endpoint

**Comment by minusdavid** [comment]
I'm seeing this error in Virtuoso version 06.01.3127 and I think I'm imitating the web UI reasonably well and that works. 

What was the motive for closing this issue in the end?

**Comment by TortugaAttack** [comment]
because at that time i was thinking of could not fix it accurately. 
Well i will reopen it

**Comment by TortugaAttack** [comment]
but could you provide your configuration (esp. your updates) 
So i can better test it? 
Would be awesome :)

**Comment by TortugaAttack** [comment]
Should work now. 
If it occurs again, i will ceck into it, but i am pretty sure its an error with virtuoso 6.x or Jena.
