### ISSUE TITLE
Parsing issue in the result file(.nt) generated after benchmarking

### ISSUE THREAD

**Issue by bajpaijalaj** [dice-group/IGUANA#101]
While running the benchmarking using the Tentris' test dataset (sp2b.nt), it was observed that the result file contained some unescaped double quotes (see in the snapshot) thereby creating a RDF parsing issue.

![image](https://user-images.githubusercontent.com/38458301/73141319-1a0a5680-4083-11ea-855c-5bd2c5c5601c.png)

**Comment by bigerl** [comment]
see pull request #102
