### ISSUE TITLE
repair pre and post hooks

### ISSUE THREAD

**Issue by tohardik** [dice-group/IGUANA#108]
Currently the triple stores are started with an external script which is called before the iguana tasks start executing. This can be changed so that iguana handles the lifecycle of the triple store.

**Comment by bigerl** [comment]
We currently have the following problem:
* pre-/posthook commands are implemented
* sometimes, when the pre- or posthook is a script, it runs successfully but blocks before returning
* consequently, iguana waits forever for the script 

A workaround could be:
* start the command in the pre-/posthook fully detached from java, but get its process ID
* poll on the process ID until it is terminated
* maybe add a timeout for polling. If the timeout is reached the process is killed

**Comment by bigerl** [comment]
e.g.: https://github.com/dice-group/tentris-paper-benchmarks/blob/v1.0/roles/iguana_suites/templates/virtuoso-start.sh

**Comment by TortugaAttack** [comment]
Added a Unit Test using the following script, using a ServerMock. 

```bash
#!/bin/bash

if [[ -f ./shouldNotExist.pid ]]
then
    echo $(date --iso-8601) - ServerMock seems to be already running
    echo If it is not running remove shouldNotExist.pid
    exit 1
fi

echo $(date --iso-8601) - Starting ServerMock

#{{ target_dir }}/triplestores/virtuoso/{{ virtuoso_version }}/virtuoso-opensource/bin/virtuoso-t -c {{ target_dir }}/triplestores/virtuoso/virtuoso-run-{{ item[1].name }}-{{ item[2].number }}.ini
#simulating waiting for another script, normally we should start netcat or similar here, but as it's not available for anyone this should do the trick.
./src/test/resources/wait5.sh


echo $(date --iso-8601) - Waiting for ServerMock to become available

while :
do
    curl -s 127.0.0.1:8023
    if [ $? -eq 0 ]
    then
        break
    fi
    sleep 2
done

echo $(date --iso-8601) - ServerMock started and accepting connections

exit 0
```

Further on added the following to the ScriptExecutor

```
	while (process.isAlive()&&(character = reader.read()) != -1){...}
```
To explicitly check if the process is still alive. 

So far I could not reproduce the issue using this.

**Comment by TortugaAttack** [comment]
In my POV the script hooks should be sufficient to start and stop the lifecycles of the stores. 
The problem with letting Iguana controlling the lifecycle directly is that you every Store has it's own lifecycle.

**Comment by bigerl** [comment]
Test sounds like a good Idea. Let's try it out then ;)

**Comment by TortugaAttack** [comment]
Adding an inheritIO() to the process Builder worked. 
Weird java process bug i guess. 
done and in 3.0.1
