### ISSUE TITLE
Outdated configuration file in Iguana v3.0.0-alpha2 release source file.

### ISSUE THREAD

**Issue by ranjithmasthikatte** [dice-group/IGUANA#112]
Hi,

I am using the "Iguana v3.0.0-alpha2" single run version of Iguana. I used the basic configuration file provided in the source code of this release but I got the below error.

![image](https://user-images.githubusercontent.com/19502082/81305715-f3df5400-907e-11ea-8eb5-c501acddcf3e.png)

I got to know that, in this version of Iguana, the syntax of the configuration file is changed. Later I used the below configuration file and Iguana ran successfully.

![image](https://user-images.githubusercontent.com/19502082/81306025-4ae52900-907f-11ea-961e-0687f552d062.png)

But I need to store the benchmarking result into a triple store, therefore could you please let me know how to modify the configuration file to store the result in a triple store as well as nt file storage. 

Brief documentation (Like all the keywords, necessary setup) on the configuration file would be very helpful to set up the Iguana configuration file based on the client requirements.

Thanks in advance.

Ranjith

**Comment by tohardik** [comment]
Hello Ranjith,

you are right, the configuration file in the repo has become outdated after we recently made changes. I have uploaded a [new configuration file](https://github.com/dice-group/IGUANA/blob/4cf6ae3a8b652ed77404d684a5a79e3e17d67c10/tentris-http.suite). It contains the documentation to help you understand the configuration.

About storing the results in the triple store: In previous versions, it was possible to specify a triple store in the configuration file to which the benchmarking results would be written. However, my analysis of the current version suggests that this functionality is broken. For now, the application will output the results in a .nt file. 

A simple solution is to upload the .nt file to your desired triple store manually. If you need to automate this, another option is to use post benchmark hook script(described in the new configuration file).

Best,
Hardik

**Comment by tohardik** [comment]
#113 is updated with the required information. Closing this.
