### ISSUE TITLE
reenable storing results to triple store

### ISSUE THREAD

**Issue by bigerl** [dice-group/IGUANA#113]
Currently, storing results to a triple store is broke as stated in #112 . 
It should be re-enabled.

**Comment by tohardik** [comment]
The implementation to store the results into a triple store is available in TriplestoreStorage class. However, the application does not allow to specify it in the IGUANA configuration file. The two aspects(1. Storage, 2. Metrics) of the benchmarking result are currently being configured in the constructor of the AbstractTask(i.e. hard-coded). Here, a default NTFileStorage is added along with 3 default Metrics. 

 To re-enable the storing of results into the triple store, following is needed: :
a) AbstractTask constructor should be updated to accept arguments which allow configuring the TriplestoreStorage as a storage
b) Support additional key/values in the IGUANA configuration file that allow defining the parameters of TriplestoreStorage(e.g. URL, password). Then, these values should be supplied to the AbstractTask constructor to complete the whole functionality.

**Comment by TortugaAttack** [comment]
Will be possible in the next release. 
The Storage configuration can be set directly in the suite configuration file.
