### ISSUE TITLE
Option to rename the benchmark result file name.

### ISSUE THREAD

**Issue by ranjithmasthikatte** [dice-group/IGUANA#114]
Hi,

In the current version of Iguana, the benchmark result file name is in the format results_task_1588853024-1-1.nt.

Could you please add a feature in the configuration file where we can rename the filename so that it will be easy to access the result file programmatically.

Thanks
Ranjith

**Comment by TortugaAttack** [comment]
Hey, 

Sorry for the late response. 
This is will be possible in the next release, which will go online some where next week. 
The configuration will change completely to YAML and the Storage can be configured such that the format name can be provided in the configuration.

**Comment by ranjithmasthikatte** [comment]
Thank You.

**Comment by TortugaAttack** [comment]
Done. Have a look at the preliminary doc at http://iguana-benchmark.eu/docs/3.0.0/usage/configuration/#storages
