### ISSUE TITLE
Add Detailed Metrics on Results

### ISSUE THREAD

**Issue by bigerl** [dice-group/IGUANA#133]
Those could include:
- ContentLength ( in Bytes)
- NumberOfSolutions ( = number of rows in result table)
- NumberOfBindings ( = number of non-empty cells in result table )
- NumberOfVariables ( = number of columns/column heads )

Example

| x        | y           |
| ------------- |:-------------:|
| 1    |   |
| 2    | 1      |
| 3 | 1      |

NOV = 2
NOB = 5
NOS = 3

**Comment by nck-mlcnv** [comment]
see `SaxSparqlJsonResultCountingParser` class
