### ISSUE TITLE
How to do sparql query on Ontop

### ISSUE THREAD

**Issue by xuchen-tech** [dice-group/IGUANA#137]
I'm doing a benchmark on Ontop. But I got below error. My question is how to configure the query?
2021-03-12 10:06:15,633 [main] ERROR [org.aksw.iguana.cc.query.impl.InstancesQueryHandler] - <could not read queries>

### My configuration:
**queriesFile: "queries.txt"**

PREFIX : <http://example.org/voc#>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>

select ?sensorData ?siid ?val WHERE {
  ?sensorData a foaf:SensorData .
  ?sensorData :Siid ?siid FILTER(?siid = 5045).
  ?sensorData :value ?val .
}

**Official query command:**
**POST** http://localhost:8080/sparql
Content-Type: application/sparql-query
Accept: application/json

PREFIX : <http://example.org/voc#>
SELECT DISTINCT ?teacher {
  ?teacher a :Teacher .
}

**My configuration:**
datasets:
  - name: "DoesNotMatter"
connections:
  - name: "benchmark"
    # endpoint: "http://139.24.23.48:8080/sparql"
    updateEndpoint: "http://139.24.23.48:8080/sparql"
tasks:
  - className: "Stresstest"
    configuration:
      #timeLimit is in ms
      timeLimit: 3600000
      queryHandler:
        className: "InstancesQueryHandler"
      workers:
        - threads: 2
          className: "SPARQLWorker"
          queriesFile: "queries.txt"
          timeOut: 180000
metrics:
  # - className: "QMPH"
  - className: "QPS"
  # - className: "NoQPH"
  # - className: "AvgQPS"
  # - className: "NoQ"

#optional otherwise an nt file will be used
storages:
  - className: "NTFileStorage"
    #configuration:
      #fileName: YOUR_RESULT_FILE_NAME.nt

**Comment by TortugaAttack** [comment]
Hey, 
Thanks for using Iguana :)

The StackTrace of the error is cut off, Could you send the complete StackTrace of the error :) 

I guess the queries file isn't loaded properly
the queries.txt file has to have one query per line. so
queriesFile: "queries.txt"
```
PREFIX : <http://example.org/voc#> PREFIX foaf: <http://xmlns.com/foaf/0.1/> select ?sensorData ?siid ?val WHERE { ?sensorData a foaf:SensorData . ?sensorData :Siid ?siid FILTER(?siid = 5045). ?sensorData :value ?val . }
```

Other than that:

**Comment by xuchen-tech** [comment]
Thanks for so quickly response, I tried your suggestions, but it still has errors. Please help me to figure out.
[benchmark.txt](https://github.com/dice-group/IGUANA/files/6127227/benchmark.txt)


[StackTrace.txt](https://github.com/dice-group/IGUANA/files/6127219/StackTrace.txt)

**Comment by xuchen-tech** [comment]
workers:
        - threads: 2
          className: "HttpPostWorker"
          contentType: "application/sparql-query"
          responseType: "application/json"
          queriesFile: "/home/program/workspace/iguana/queries.txt"
          timeOut: 180000
          
Now Server doesn't report error, but when I run IGuana, the log shows that 

<Starting Worker[{HttpGetWorker} : {1}].>

What I configured is **HttpPostWorker**

**Comment by TortugaAttack** [comment]
`<Starting Worker[{HttpGetWorker} : {1}].>`

Ah that is a logging issue. 
THe HttpPostWorker extends the HttpGetWorker but apperently doesn't override the LOGGER. 
So you can ignore that there stands HttpGetWorker

Regarding: ` org.springframework.web.bind.MissingRequestHeaderException: Missing request header 'Accept' for method parameter of type String`
I will look into that and keep you updated. Normally it should send the Post request correctly. 

The queryResults will be saved into an ntriple file located in your folder.
For more details on how to read them: http://iguana-benchmark.eu/docs/3.2/usage/results/

**Comment by xuchen-tech** [comment]
Thanks for you support. fixed.
