### ISSUE TITLE
Unknown keyword when starting Iguana

### ISSUE THREAD

**Issue by gatemezing** [dice-group/IGUANA#156]
Hello,
I just downloaded Iguana and I was following the tutorial at http://iguana-benchmark.eu/docs/3.3/usage/tutorial/. 
When I start the script I have the error depicted in the screenshot. Here (https://gist.github.com/gatemezing/c66165f3a243e012e10552f22f1f2bba) the config file used for my test
Inspecting the log, there is this line: 
`2022-04-04 12:09:00,796 [main] WARN [com.networknt.schema.JsonMetaSchema] - <Unknown keyword then - you should define your own Meta Schema. If the keyword is irrelevant for validation, just use a NonValidationKeyword`
![Capture d’écran 2022-04-04 à 16 43 45](https://user-images.githubusercontent.com/922883/161569128-2a8cc6d9-3591-4fd9-a95a-1472f84d505d.png)
>

**Comment by bigerl** [comment]
Hi Ghislain,

we are currently figuring out who can help you best with your issue. We'll come back to you soon.

**Comment by nkaralis** [comment]
Hello Ghislain,

In the configuration file that you shared with us, you have not specified a dataset (the dataset part is commented out).
Your configuration should provide at least one dataset (workflow: http://iguana-benchmark.eu/docs/3.3/usage/workflow/).
Please update your configuration and let us know if it works.

**Comment by gatemezing** [comment]
Hi @nkaralis , sorry for the delay. 
Thanks for your answer. If I understand you correctly, I need to have a key property "datasets" even if all my test will be used on a SPARQL endpoint. Is that correct?

**Comment by bigerl** [comment]
Yes. You need to give your dataset at least a name. see also http://iguana-benchmark.eu/docs/3.3/usage/configuration/#datasets

**Comment by gatemezing** [comment]
Thanks  @bigerl and @nkaralis. It works. I will close the issue right after.
