### ISSUE TITLE
Invalid (post) request body encoding

### ISSUE THREAD

**Issue by Clueliss** [dice-group/IGUANA#172]
IGUANA sends the bodies of (at least) POST update requests in the wrong encoding. Meaning e.g. Umlaute are not encoded properly.
To reproduce just send e.g. a `DELETE DATA` with an umlaut in an update to a triplestore, the incoming body will be wrongly encoded.

One fix for it can be seen [here](https://github.com/dice-group/IGUANA/compare/v3.2.1...Clueliss:IGUANA:fix/request-encoding).

Although I don't know if this is the proper fix, since in earlier versions such as [v3.0.2](https://github.com/dice-group/IGUANA/blob/v3.0.2/iguana.corecontroller/src/main/java/org/aksw/iguana/cc/worker/impl/HttpPostWorker.java#L59) it works properly without that fix.

**Comment by frensing** [comment]
I could recreate the issue, but did not find out why it has worked before in the older version.
Your fix seems to be the right way that I also found online.

**Comment by bigerl** [comment]
addressed in #179
