### ISSUE TITLE
IGUANA does not handle responses that are successful but not 200-ok correctly

### ISSUE THREAD

**Issue by Clueliss** [dice-group/IGUANA#175]
Some SPARQL updates return 204-no-content on some triplestores (e.g. fuseki, graphdb) and IGUANA does not handle this. It marks the queries as failed when that happens.

For potential fixes see [compare](https://github.com/Clueliss/IGUANA/compare/v3.2.2...v3.2.4)

**Comment by frensing** [comment]
Thanks for your fix idea! The fix has been implemented in PR #180.
