### ISSUE TITLE
Correct the try-with-resource-block in the CLIWorker

### ISSUE THREAD

**Issue by nck-mlcnv** [dice-group/IGUANA#204]
Change the line:
https://github.com/dice-group/IGUANA/blob/efd02d5d4506a20428698c2831dd30af0543a427/iguana.corecontroller/src/main/java/org/aksw/iguana/cc/worker/impl/CLIWorker.java#L54

to something like this:

```
try (InputStreamReader isr = new InputStreamReader(process.getInputStream());
     BufferedReader br = new BufferedReader(isr)) {
```

**Comment by ELBuenFercho** [comment]
The original line of code should work correctly, are you just trying to make it more readable?

**Comment by nck-mlcnv** [comment]
It does work fine normally, but if the constructor of the BufferedReader throws an exception, the InputStream won't be closed. 
See: https://stackoverflow.com/a/1388772

**Comment by nck-mlcnv** [comment]
The CLI-Worker will be removed with the new upcoming release

**Comment by nck-mlcnv** [comment]
close as not planned
