### ISSUE TITLE
Benchmark different versions of triple stores

### ISSUE THREAD

**Issue by tomatophantastico** [dice-group/IGUANA#60]
Test not only the most recent version of a triple store, but also major old ones, like 
Virtuoso 6.0.0, 6.1.8, 7.0.0., 7.1.0. to evaluate progress in performance.

This could even be scripted, benchmarking all tagged commits.

**Comment by TortugaAttack** [comment]
Hey, 
Thanks a lot for the participation! :)

I was thinking about comparing virtuoso 6x and 7x 
as well as blazegraph 1.5x and 2.x 

But your script solution of comparing each tag is very interesting. I will think about that :)
