### ISSUE TITLE
[CC][DG] data generator in eclipse

### ISSUE THREAD

**Issue by JessicaAlphy** [dice-group/IGUANA#83]
Thank you for your perfect project, I am importing the project into the eclipse on the windows OS. The project can be built success. But I have no idea: 
① How to run the project, (call MainController.java? or  DataGeneratorController.java)
I attemptted to run both the two classes, but no result shows in the console. :( . 
② Which configuration file I need to set, where to set the input parameter?  (iguana.controller.src.main.resources.iguana.properties file? )  where to write the following settings:
```
<random-function class="org.aksw.iguana.generate.DatasetGeneratorImpl" generate="true" initFile="dataset100.nt" roh="0.7" ch="0.7">
			<percent value="1.0" file-name="dataset100.nt" /> <!-- only if you want to test too--> 
			<percent value="0.5" file-name="dataset50.nt" />
			<percent value="0.2" file-name="dataset20.nt" />
			<percent value="0.1" file-name="dataset10.nt" />
</random-function>
```
 ③ Which main class should be called， if the DataGeneratorController.java should be invoked first, how to set the input arguments?
**Thank you in advance.**

**Comment by TortugaAttack** [comment]
Hi, 
Currently there is no implementation of a DatasetGenerator, (the one in the old version was just not good and useless) 

1) Iguana can be started using the CoreController and ResultProcessor as a daemon process. See https://github.com/dice-group/IGUANA/wiki/Installation
The DataGenerator is ia module of the CoreController.
2) What you are using as the config is from the old version. The new version uses https://github.com/dice-group/IGUANA/wiki/config#iguana-config and you can send it to the corecontroller daemon using https://github.com/dice-group/IGUANA/wiki/installation#how-to-execute-an-iguana-config-a-benchmark
3) please see 1) and 2) 

hope this helps.

**Comment by JessicaAlphy** [comment]
Thank you for your response. 

Do you mean that the link address https://github.com/AKSW/mosquito in the paper "(DBPSB) DBpedia SPARQL Benchmark – Performance Assessment with Real Queries on Real Data" is the old version, right?
In the manuscript DBPSB(ISWC 2011) of Page3 and Page 4,   it states as follows:

> For generating smaller datasets, we investigated two different methods. The first method (called “rand”)......, the second method (called “seed”) .......

 Now, I would like to generate a small scale of DBpedia dataset with your proposed method as you mentioned in the paper, but when I run the github project, I did not know the detail about how to go on. Could you please teach me how to generate a small scale DBpedia dataset with the IGUANA project?
 **Many thanks.**

**Comment by TortugaAttack** [comment]
There is a link in that Paper towards that site? 
No that is the same github page as this. 

The DBPSB of 2011 has also nothing todo with IGUANA itself, as Iguana was developed later in 2014/2015. And the procedure to create smaller datasets was integrated in the first version of Iguana but was malicious, wrong and generally RAM intense. 
So we dropped it. 

The rand implementation was as far as i know just random triples until the desired size is reached. Random is a problematic use here, as the procedure ignores any structure the previous dataset had and does not represent a smaller version of that dataset. If that is no matter, you can easily write a script to create such a dataset.  Iguana is of no use here.
a naive approach using one NTriple File (could be extended easily to multiple files): 
```
getRandomLines(int datasetSize, int desiredSize, File inputFile, File outputFile){
  Set<Integer> lineNumbers = new HashSet<Integer>();
  Random rand = new Random(System.currentTimeInMillis());
  while(lineNumbers.size()<desiredSize){
    int nextLine = rand.nextInt(datasetSize);
    if(!lineNumbers.contains(nextLine)){
       lineNumbers.add(nextLine);
    }
  }
  printLines(lineNumbers, inputFile, outputFule);
}

printLines(Set<Integer> lineNumbers,File inputFile, File outputFile){
  PrintWriter pw = new PrintWriter(outputFile);
  for(Integer lineNo : lineNumbers){
    pw.println(FileUtils.getLineAt(lineNo, inputFile));
  }

}
```
The seed implementation is a bit more complex and the use of it is discussable. The procedure is described in 
"Apples and Oranges: A Comparison ofRDF Benchmarks and Real RDF Dataset" by Duan et al.
The paper describes a procedure to preserve the structure, but they define what the structure is, so it is kinda problematic too. 
As far as i know there is no code online available any more.

**Comment by JessicaAlphy** [comment]
Thank you. I think I kind of got it, thank you for your response and kindness. I will try to implement the desired size of the dataset as you taught me. By the way, what is the main intention of the IGUANA  project?

**Comment by TortugaAttack** [comment]
awesome!
Iguana is basically a platform to execute SPARQL benchmarks as automatized and comparable as possible.
