### ISSUE TITLE
redundant code

### ISSUE THREAD

**Issue by bigerl** [dice-group/IGUANA#89]
https://github.com/dice-group/IGUANA/blob/fa52e3a6104b62c809f60d073f261c37f5b119d8/iguana.taskprocessor/src/main/java/org/aksw/iguana/tp/tasks/impl/stresstest/worker/impl/CLIInputWorker.java#L46
and
https://github.com/dice-group/IGUANA/blob/fa52e3a6104b62c809f60d073f261c37f5b119d8/iguana.taskprocessor/src/main/java/org/aksw/iguana/tp/tasks/impl/stresstest/worker/impl/MultipleCLIInputWorker.java#L47
use mostly the same code.

**Comment by tohardik** [comment]
This is done.
