### ISSUE TITLE
storing results in TriplestoreStorage is not working.

### ISSUE THREAD

**Issue by ranjithmasthikatte** [dice-group/IGUANA#91]
Hi,

I am using iguana-single-run and I would like to store the results of Iguana in a triple store database. For this, I updated the configuration file as below. But the results are not stored in a triple store, it's stored in nt file. 

![image](https://user-images.githubusercontent.com/19502082/72065538-c2c46200-32de-11ea-8b7a-54a5de967922.png)

Please let me know what is the issue.
Thanks in advance.

**Comment by bigerl** [comment]
probably related to #101 . the triple store might reject it because of wrong formatting.

**Comment by bajpaijalaj** [comment]
The Iguana single-run jar file which we were using since December end has this(#101) issue fixed.  I think Ranjith still couldn't get it to work. I regenerated the single-run jar file with the fix so that the team could continue with the dev work.
